// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Unit2Project.Models;

#nullable disable

namespace Unit2Project.Migrations
{
    [DbContext(typeof(VideogameContext))]
    partial class VideogameContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Unit2Project.Models.Videogame", b =>
                {
                    b.Property<int>("VideogameID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VideogameID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Rating")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("YearReleased")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("VideogameID");

                    b.ToTable("Videogames");

                    b.HasData(
                        new
                        {
                            VideogameID = 1,
                            Name = "Modern Warfare 2",
                            Rating = 5,
                            YearReleased = 2009
                        },
                        new
                        {
                            VideogameID = 2,
                            Name = "Wonder Woman",
                            Rating = 3,
                            YearReleased = 2017
                        },
                        new
                        {
                            VideogameID = 3,
                            Name = "Moonstruck",
                            Rating = 4,
                            YearReleased = 1988
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
